const express = require("express");
const newapis = require("../../myapis");

const organization = require("../../Services/Organization/organization.route");
const analytics = require("../../Services/Analytics/analytics.route");
const schedule = require("../../Services/Schedules/schedule.route");
const building = require("../../Services/Building/building.route");
const bacnet = require("../../Services/Bacnet/bacnet.route");
const gateway = require("../../Services/Gateway/gateway.route");
const parking = require("../../Services/Parking/parking.route");
const campus = require("../../Services/Campus/campus.route");
const device = require("../../Services/Device/device.route");
// const alert = require("../../Services/Alerts/alert.route");
const glalert = require("../../Services/Gl_Alerts/alert.route");
const floor = require("../../Services/Floor/floor.route");
const image = require("../../Services/Image/image.route");
const light = require("../../Services/Lights/light.route");
const auth = require("../../Services/Auth/auth.route");
const zone = require("../../Services/Zone/zone.route");
const time = require("../../Services/Misc/time");
const backup = require("../../Services/Backup/mysqlBackup.route");
const dataupload = require("../../Services/DataUpload/dataUpload.route");
const coworking = require("../../Services/Coworking/coworking.route");
const glZone = require("../../Services/GlZone/glZone.route");
const gl_zone = require("../../Services/Gl_zone/Gl_zone.route");
const gl_zone_booking = require("../../Services/Gl_zone_booking/Gl_zone_booking.route");
const subsystem = require("../../Services/Subsystem/subsystem.route");
const Gl_analytics = require("../../Services/Gl_analytics/Gl_analytics.route");
const area = require("../../Services/Area/area.route");
const hvac_schedule = require("../../Services/Hvac_schedules/hvac_schedule.route");
const hvac_recurring_schedule = require("../../Services/Hvac_recuuring_schedule/hvac_recuuring_schedule.route");
const dag = require("../../Services/Gl_Dag/dag.route");
const Gl_user = require("../../Services/Gl_user/Gl_user.route");
const Gl_Schedules = require("../../Services/Gl_Schedules/schedule.route");
const GL_PAS = require("../../Services/Gl_PAS/PAS_route");
const Gl_ibms_analytics = require("../../Services/Gl_IBMS_Analytics/ibms.analytics.route");
// const Gl_reports = require("../../Services/Gl_reports/Gl_reports.route");
const Gl_reports = require("../../Services/Energy_analytics/Analytics_reports.route");
const cpm = require("../../Services/Cpm/cpm.route");
const customerApi = require("../../Services/CustomerApi/customer_api.route");

const router = express.Router();

router.use("/organizations", organization);
router.use("/glZone", glZone);
router.use("/gl_zone", gl_zone);
router.use("/gl_zone_booking", gl_zone_booking);
router.use("/subsystem", subsystem);
router.use("/gl_analytics", Gl_analytics);
router.use("/analytics", analytics);
router.use("/buildings", building);
router.use("/bacnet", bacnet);
router.use("/schedules", schedule);
router.use("/gateways", gateway);
router.use("/campuses", campus);
router.use("/devices", device);
router.use("/lights", light);
// router.use("/alerts", alert);
router.use("/gl_alerts", glalert);

router.use("/floors", floor);
router.use("/image", image);
router.use("/zones", zone);
router.use("/time", time);
router.use("/auth", auth);
router.use("/areas", area);
router.use("/backup", backup);
router.use("/coworking", coworking);
router.use("/newapis", newapis);
router.use("/hvac_schedules", hvac_schedule);
router.use("/hvac_recuuring_schedule", hvac_recurring_schedule);
router.use("/dag", dag);
router.use("/gl_user", Gl_user);
router.use("/gl_schedules", Gl_Schedules);
router.use("/gl_pas", GL_PAS);
router.use("/gl_ibms_analytics", Gl_ibms_analytics);
router.use("/gl_reports", Gl_reports);
router.use("/cpm", cpm);
// router.use("/calc-engine", Gl_calc_engine);
router.use("/customer-api", customerApi);

router.use("/dataupload", dataupload);

module.exports = router;
